// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAK51CF3pXntpvJSxxtzdzjxsYaqz1-xfA',
    appId: '1:1013782480038:web:72538989ef14138c3b2067',
    messagingSenderId: '1013782480038',
    projectId: 'samyak-365cd',
    authDomain: 'samyak-365cd.firebaseapp.com',
    storageBucket: 'samyak-365cd.firebasestorage.app',
    measurementId: 'G-DDTSK64GBY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCvbGw4AtO7fbYyMwfmentx7BcyOki0-4o',
    appId: '1:1013782480038:android:e9917ff5570059483b2067',
    messagingSenderId: '1013782480038',
    projectId: 'samyak-365cd',
    storageBucket: 'samyak-365cd.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAvCuhmzQDXVSQoVnP7rmOU_U8C8LysOAY',
    appId: '1:1013782480038:ios:7ac3c56704b5e6263b2067',
    messagingSenderId: '1013782480038',
    projectId: 'samyak-365cd',
    storageBucket: 'samyak-365cd.firebasestorage.app',
    iosBundleId: 'com.example.samyak',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAvCuhmzQDXVSQoVnP7rmOU_U8C8LysOAY',
    appId: '1:1013782480038:ios:7ac3c56704b5e6263b2067',
    messagingSenderId: '1013782480038',
    projectId: 'samyak-365cd',
    storageBucket: 'samyak-365cd.firebasestorage.app',
    iosBundleId: 'com.example.samyak',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAK51CF3pXntpvJSxxtzdzjxsYaqz1-xfA',
    appId: '1:1013782480038:web:7a11a89918393c873b2067',
    messagingSenderId: '1013782480038',
    projectId: 'samyak-365cd',
    authDomain: 'samyak-365cd.firebaseapp.com',
    storageBucket: 'samyak-365cd.firebasestorage.app',
    measurementId: 'G-Z34GGXWFZH',
  );
}
